document.writeln("    <div align=\"center\"> <table border=\"0\" width=\"965\" bgcolor=\"#E1EDFA\" >");
document.writeln("                              <tr><td >");
document.writeln("   <div align=\"right\"><font size=\"2\"><strong>站点导航：</strong>");
document.writeln("       <a href=\"http://www.1268.cn\" target=\"_blank\">1268站长网</a>");
document.writeln("       <a href=\"http://www.wuxiashu.net\" target=\"_blank\">武侠书大全</a>");
document.writeln("       <a href=\"http://www.166book.com\" target=\"_blank\">166图书网</a>");
document.writeln("       <a href=\"http://www.songbaisheng.com\" target=\"_blank\">松柏生全集</a>");
document.writeln("       <a href=\"#\" onClick=\"javascript:window.external.AddFavorite(\'http://www.songbaisheng.com\',\'松柏生小说大全\')\" title=\"收藏本站到你的收藏夹\">收藏本站</a>");
document.writeln("     <a href=# onClick=\"this.style.behavior=\'url(#default#homepage)\';this.setHomePage(\'http://www.songbaisheng.com\');\">设为首页</a></font></div></td></tr></table>");
document.writeln(" <table border=\"0\" cellpadding=\"0\" cellspacing=\"1\" width=\"965\" bgcolor=\"#FFFFFF\" height=\"61\"  style=\"border: 1 dotted #008000\"><tr> <td><a href=\"http://www.songbaisheng.com\" target=\"_parent\" title=\"松柏生全集\"><img src=\"/logo.jpg\" width=\"237\" height=\"60\" /></a>");
document.writeln("</td><td><a href=\"/\" target=\"_parent\" title=\"首页\"><img src=\"/js/jinggao.png\"  /></a></td></tr>");
document.writeln("</table></div>");
document.writeln("<table align=\"center\" width=\"965\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#FFFFFF\"> ");
document.writeln(" <tr> <td width=\"11%\" height=\"5\"><font size=\"2\"><img border=\"0\" src=\"/js/icon.gif\" width=\"15\" height=\"14\"><a href=\"http://www.songbaisheng.com/\">首页</a></font></td>");
document.writeln("<td width=\"11%\" height=\"5\"><font size=\"2\"><img border=\"0\" src=\"/js/icon.gif\" width=\"15\" height=\"14\"><a href=\"http://www.wuxiashu.net/wuxia/\">武侠小说大全</a></font></td>");
document.writeln("<td width=\"11%\" height=\"5\"><font size=\"2\"><img border=\"0\" src=\"/js/icon.gif\" width=\"15\" height=\"14\"><a href=\"http://www.wuxiashu.net/zhentan/\">侦探小说合集</a></font></td>");
document.writeln("<td width=\"11%\" height=\"5\"><font size=\"2\"><img border=\"0\" src=\"/js/icon.gif\" width=\"15\" height=\"14\"><a href=\"http://www.wuxiashu.net/xiyouji/\">西 游 记</a></font></td>");
document.writeln("<td width=\"11%\" height=\"5\"><font size=\"2\"><img border=\"0\" src=\"/js/icon.gif\" width=\"15\" height=\"14\"><a href=\"http://www.wuxiashu.net/sanguo/\">三国演义</a></font></td>");
document.writeln("<td width=\"11%\" height=\"5\"><font size=\"2\"><img border=\"0\" src=\"/js/icon.gif\" width=\"15\" height=\"14\"><a href=\"http://www.wuxiashu.net/shuihuzhuan/\">水浒传</a></font></td>");
document.writeln("<td width=\"11%\" height=\"5\"><font size=\"2\"><img border=\"0\" src=\"/js/icon.gif\" width=\"15\" height=\"14\"><a href=\"http://www.wuxiashu.net/hongloumeng/\">红楼梦</a></font></td>");
document.writeln("<td width=\"11%\" height=\"5\"><font size=\"2\"><img border=\"0\" src=\"/js/icon.gif\" width=\"15\" height=\"14\"><a href=\"http://www.wuxiashu.net/wenxue/\">世界文学名著</a></font></td> ");
document.writeln("<td width=\"11%\" height=\"5\"><font size=\"2\"><img border=\"0\" src=\"/js/icon.gif\" width=\"15\" height=\"14\"><a href=\"http://www.wuxiashu.net/qianzexiaoshuo/\">四大谴责小说</a></font></td>     </tr> ");
document.writeln("    <tr> <td width=\"11%\" height=\"5\"><font size=\"2\"><img border=\"0\" src=\"/js/icon.gif\" width=\"15\" height=\"14\"><a href=\"http://www.wuxiashu.net/lishitanan/\">历史探案小说</a></font></td>	");
document.writeln("<td width=\"11%\" height=\"5\"><font size=\"2\"><img border=\"0\" src=\"/js/icon.gif\" width=\"15\" height=\"14\"><a href=\"http://www.wuxiashu.net/kanaiji/\">卡耐基系列集</a></font></td> ");
document.writeln("<td width=\"11%\" height=\"5\"><font size=\"2\"><img border=\"0\" src=\"/js/icon.gif\" width=\"15\" height=\"14\"><a href=\"http://www.wuxiashu.net/keji/\">世界科技全景</a></font></td> ");
document.writeln("<td width=\"11%\" height=\"5\"><font size=\"2\"><img border=\"0\" src=\"/js/icon.gif\" width=\"15\" height=\"14\"><a href=\"http://www.wuxiashu.net/kehuan/\">世界科幻小说</a></font></td> ");
document.writeln("<td width=\"11%\" height=\"5\"><font size=\"2\"><img border=\"0\" src=\"/js/icon.gif\" width=\"15\" height=\"14\"><a href=\"http://www.wuxiashu.net/jiankangshenghuo/\">健康生活百科</a></font></td> ");
document.writeln("<td width=\"11%\" height=\"5\"><font size=\"2\"><img border=\"0\" src=\"/js/icon.gif\" width=\"15\" height=\"14\"><a href=\"http://www.wuxiashu.net/ershiwushi/\">二十五史专题</a></font></td> ");
document.writeln("<td width=\"11%\" height=\"5\"><font size=\"2\"><img border=\"0\" src=\"/js/icon.gif\" width=\"15\" height=\"14\"><a href=\"http://www.wuxiashu.net/gudian/\">古典小说全集</a></font></td> ");
document.writeln("<td width=\"11%\" height=\"5\"><font size=\"2\"><img border=\"0\" src=\"/js/icon.gif\" width=\"15\" height=\"14\"><a href=\"http://www.wuxiashu.net/caigentan/\">菜根谭系列</a></font></td>");
document.writeln("<td width=\"11%\" height=\"5\"><font size=\"2\"><img border=\"0\" src=\"/js/icon.gif\" width=\"15\" height=\"14\"><a href=\"http://www.wuxiashu.net/baijiajiangtan/\">百家讲坛系列</a></font></td></tr> </table>");
document.writeln("<hr align=\"center\" size=\"1\" width=\"965\" noshade=\"noshade\" class=\"green\">");
